name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.2.0
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  yaml: ^3.1.0
  resource_portable: ^3.0.0
  path: ^1.6.2
  file: ^6.0.0
  archive: ^3.1.2
  platform: ^3.0.0
  process: ^4.1.0
  meta: ^1.1.6
  intl: ^0.17.0
  tool_mobile:
    git: https://github.com/felixgabler/tool_mobile.git

dev_dependencies:
  test: ^1.16.8
  test_api: ^0.3.0
  mockito: ^4.1.0
  pedantic: ^1.11.0
  quiver: '>=2.0.0 <3.0.0'
  collection: any

executables:
  screenshots: main
