name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 3.0.0
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  args: ^2.2.0
  yaml: ^3.1.0
  resource_portable: ^3.0.0
  path: ^1.8.0
  file: ^6.1.0
  archive: ^3.1.2
  platform: ^3.0.0
  process: ^4.2.1
  meta: ^1.3.0
  intl: ^0.17.0
  tool_mobile:
    git: https://github.com/felixgabler/tool_mobile.git

dev_dependencies:
  test: any
  test_api: any
  mockito: ^5.0.15
  pedantic: ^1.11.1
  quiver: '>=2.0.0 <3.0.0'
  collection: any

executables:
  screenshots: main
