name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 3.0.1
homepage: https://github.com/mmcc007/screenshots

publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  args: ^2.3.2
  yaml: ^3.1.1
  resource_portable: ^3.0.1
  path: ^1.8.2
  file: ^6.1.4
  archive: ^3.3.2
  platform: ^3.1.0
  process: ^4.2.4
  meta: ^1.8.0
  tool_mobile:
    git: https://github.com/felixgabler/tool_mobile.git

dev_dependencies:
  test: any
  mockito: ^5.3.2
  pedantic: ^1.11.1
  quiver: ^3.2.1
  collection: any

executables:
  screenshots: main
